// DISCENTE: WESLLEY SILVA - RA: 2410257



import javax.swing.JOptionPane;

/**
 *
 * @author Wes
 */
public class JanPrinc extends javax.swing.JFrame {

    /**
     * Creates new form JanPrinc
     */
    public JanPrinc() {
        initComponents();
        setLocationRelativeTo(null);
    }
    public void sair(){
        int resp = JOptionPane.showConfirmDialog(
                null,
                "Deseja realmente sair?",
                "Saida",
                JOptionPane.YES_NO_OPTION
            );
        if(resp == 0){
            dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_Principal = new javax.swing.JLabel();
        barMenuPrinc = new javax.swing.JMenuBar();
        menuPrinc = new javax.swing.JMenu();
        menuPrincCad = new javax.swing.JMenu();
        Equino = new javax.swing.JMenuItem();
        Bovino = new javax.swing.JMenuItem();
        menuRelatoriosAnimais = new javax.swing.JMenu();
        Equino1 = new javax.swing.JMenuItem();
        Bovino1 = new javax.swing.JMenuItem();
        Geral = new javax.swing.JMenuItem();
        menuItem_Sair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label_Principal.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        label_Principal.setText("Principal");

        menuPrinc.setText("Principal");

        menuPrincCad.setText("Cadastrar Animal");

        Equino.setText("Equino");
        Equino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquinoActionPerformed(evt);
            }
        });
        menuPrincCad.add(Equino);

        Bovino.setText("Bovino");
        Bovino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BovinoActionPerformed(evt);
            }
        });
        menuPrincCad.add(Bovino);

        menuPrinc.add(menuPrincCad);

        menuRelatoriosAnimais.setText("Relatórios");

        Equino1.setText("Equino");
        Equino1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Equino1ActionPerformed(evt);
            }
        });
        menuRelatoriosAnimais.add(Equino1);

        Bovino1.setText("Bovino");
        Bovino1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bovino1ActionPerformed(evt);
            }
        });
        menuRelatoriosAnimais.add(Bovino1);

        Geral.setText("Geral");
        Geral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeralActionPerformed(evt);
            }
        });
        menuRelatoriosAnimais.add(Geral);

        menuPrinc.add(menuRelatoriosAnimais);

        menuItem_Sair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuItem_Sair.setText("Sair");
        menuItem_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_SairActionPerformed(evt);
            }
        });
        menuPrinc.add(menuItem_Sair);

        barMenuPrinc.add(menuPrinc);

        setJMenuBar(barMenuPrinc);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(278, 278, 278)
                .addComponent(label_Principal)
                .addContainerGap(301, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(label_Principal)
                .addContainerGap(206, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItem_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_SairActionPerformed
        sair();
    }//GEN-LAST:event_menuItem_SairActionPerformed

    private void EquinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquinoActionPerformed
        Cadastro_Equino.getCadEquiUnic().setVisible(true);
    }//GEN-LAST:event_EquinoActionPerformed

    private void Equino1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Equino1ActionPerformed
        Relatorio_Equino.getRelAnimaisUniq().setVisible(true);
    }//GEN-LAST:event_Equino1ActionPerformed

    private void BovinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BovinoActionPerformed
        Cadastro_Bovino.getCadBovUnic().setVisible(true);
    }//GEN-LAST:event_BovinoActionPerformed

    private void Bovino1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bovino1ActionPerformed
        Relatorio_Bovino.getRelBovinoUniq().setVisible(true);
    }//GEN-LAST:event_Bovino1ActionPerformed

    private void GeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeralActionPerformed
        Relatorio_Geral.getRelGeralUnic().setVisible(true);
    }//GEN-LAST:event_GeralActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanPrinc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanPrinc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanPrinc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanPrinc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanPrinc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Bovino;
    private javax.swing.JMenuItem Bovino1;
    private javax.swing.JMenuItem Equino;
    private javax.swing.JMenuItem Equino1;
    private javax.swing.JMenuItem Geral;
    private javax.swing.JMenuBar barMenuPrinc;
    private javax.swing.JLabel label_Principal;
    private javax.swing.JMenuItem menuItem_Sair;
    private javax.swing.JMenu menuPrinc;
    private javax.swing.JMenu menuPrincCad;
    private javax.swing.JMenu menuRelatoriosAnimais;
    // End of variables declaration//GEN-END:variables
}
