// DISCENTE: WESLLEY SILVA - RA: 2410257



import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Relatorio_Geral extends javax.swing.JFrame {
     static Relatorio_Geral relGeralUnic;
    /**
     * Creates new form Relatorio_Geral
     */
    public Relatorio_Geral() {
        initComponents();
        setLocationRelativeTo(null);
    }
    public static Relatorio_Geral getRelGeralUnic(){
        if(relGeralUnic == null){
            relGeralUnic = new Relatorio_Geral();
        }
        return relGeralUnic;
    }
    
     public void sair(){
        int resp = JOptionPane.showConfirmDialog(
                null,
                "Deseja realmente sair?",
                "Saida",
                JOptionPane.YES_NO_OPTION
        );
        if(resp == 0){
            dispose();
        }
    }
     
      public void listTabCav(){
        DefaultTableModel modelo = (DefaultTableModel)tbRelEquino.getModel();
        int posLin = 0;
        
        modelo.setRowCount(posLin);
        
        for(Equino cav:GerEquino.getGerEquinoUnic().getBdEquino()){ //for each
            modelo.insertRow(posLin, new Object[]{
                cav.getCodAnimal(),
                cav.getIdadeAnimal(),
                cav.getAlturaEquino(),
                cav.getPerimetroToracico(),
                cav.getPesoAnimal(),
                cav.getDoencaAnimal()
            });
            posLin++;
        }
    }
    public void listTabBov(){
        DefaultTableModel modelo = (DefaultTableModel)tbRelBovino.getModel();
        int posLin = 0;
        
        modelo.setRowCount(posLin);
        
        for(Bovino bov : GerBovino.getBovUnic().getBdBovino()){ //for each
            modelo.insertRow(posLin, new Object[]{
                bov.getCodAnimal(),
                bov.getIdadeAnimal(),
                bov.getPesoAnimal(),
                bov.getPesoEmArroba(),
                bov.getDoencaAnimal()
            });
            posLin++;
        }
    }
    
    public void selectTabCav(){
    
        String valLinTab = "";
        
        int posLin = tbRelEquino.getSelectedRow();
        int col = 0;
        for(col = 0; col < tbRelEquino.getColumnCount(); col++){
            valLinTab += tbRelEquino.getModel().getValueAt(posLin, col).toString();
            
            if(col+1 < tbRelEquino.getColumnCount()){
                valLinTab += " - ";
            }
        }
        
        JOptionPane.showMessageDialog(
                null,
                "Conteudo: " + valLinTab,
                "VALORES DA LINHA --> "+ (posLin + 1),
                1
        );
    }
    public void selectTabBov(){
    
        String valLinTab = "";
        
        int posLin = tbRelBovino.getSelectedRow();
        int col = 0;
        for(col = 0; col < tbRelBovino.getColumnCount(); col++){
            valLinTab += tbRelBovino.getModel().getValueAt(posLin, col).toString();
            
            if(col+1 < tbRelBovino.getColumnCount()){
                valLinTab += " - ";
            }
        }
        
        JOptionPane.showMessageDialog(
                null,
                "Conteudo: "+valLinTab,
                "VALORES DA LINHA --> "+ (posLin + 1),
                1
        );
    }
    
    private void calcularPesoTotal(){
        Double sum = 0.0;
        for(Bovino bov : GerBovino.getBovUnic().getBdBovino()){
            sum += bov.getPesoAnimal();
        }
        for(Equino cav : GerEquino.getGerEquinoUnic().getBdEquino()){
            sum += cav.getPesoAnimal();
        }
        lb_PesoTotal.setText("Peso Total: "+ sum);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbRelEquino = new javax.swing.JTable();
        btn_SAir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbRelBovino = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        lb_PesoTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Relatório Geral");

        tbRelEquino.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "IDADE", "ALTURA", "P.T", "PESO", "DOENÇA"
            }
        ));
        tbRelEquino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbRelEquinoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbRelEquino);

        btn_SAir.setText("Sair");
        btn_SAir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SAirActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Bovinos");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Equinos");

        tbRelBovino.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "IDADE", "PESO", "PESO EM @", "DOENÇA"
            }
        ));
        tbRelBovino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbRelBovinoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbRelBovino);

        lb_PesoTotal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb_PesoTotal.setText("Peso Total:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
                                .addComponent(jScrollPane1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_SAir)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lb_PesoTotal)
                        .addGap(183, 183, 183))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_PesoTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btn_SAir)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbRelEquinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbRelEquinoMouseClicked
        selectTabCav();
    }//GEN-LAST:event_tbRelEquinoMouseClicked

    private void btn_SAirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SAirActionPerformed
        sair();
    }//GEN-LAST:event_btn_SAirActionPerformed

    private void tbRelBovinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbRelBovinoMouseClicked
        selectTabBov();
    }//GEN-LAST:event_tbRelBovinoMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        listTabCav();
        listTabBov();
        calcularPesoTotal();
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Relatorio_Geral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Relatorio_Geral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Relatorio_Geral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Relatorio_Geral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Relatorio_Geral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_SAir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lb_PesoTotal;
    private javax.swing.JTable tbRelBovino;
    private javax.swing.JTable tbRelEquino;
    // End of variables declaration//GEN-END:variables
}
