/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1;

import javax.swing.JOptionPane;


/**
 *
 * @author Wes
 */
public class Cadastro_Equino extends javax.swing.JFrame {

    static Cadastro_Equino cadEquiUnic;
    
    private Cadastro_Equino() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public static Cadastro_Equino getCadEquiUnic(){
        if(cadEquiUnic == null){
            cadEquiUnic = new Cadastro_Equino();
        }
        return cadEquiUnic;
    }
    
    public void insEquino(){
        Equino cav = new Equino();
        
        cav.setCodAnimal(Integer.parseInt(cx_CodAnimal.getText()));
        cav.setIdadeAnimal(Integer.parseInt(cx_IdadeEquino.getText()));
        cav.setAlturaEquino(Double.parseDouble(cx_AlturaEquino.getText()));
        cav.setPerimetroToracico(Double.parseDouble(cx_PerimetroEquino.getText()));
        
        if(btn_DoencaSim.isSelected()){
            cav.setDoencaAnimal(true);
        } else {
            cav.setDoencaAnimal(false);
        }
        cav.setPesoAnimal(cav.calcPeso(cav.getPerimetroToracico()));
            
        cav = GerEquino.getGerEquinoUnic().cadEquino(cav);
        
        if(cav != null){
            JOptionPane.showMessageDialog(
                    null,
                    "Animal Cadastrado com Sucesso!",
                    "Inserção de Animal",
                    JOptionPane.INFORMATION_MESSAGE
            );
        }
        else{
            JOptionPane.showMessageDialog(
                null,
                "O Animal já está cadastrado!",
                "Erro Inserção de Animal",
                JOptionPane.ERROR_MESSAGE
            );
        }
        
        limpar();
    }
    
    public void limpar (){
        cx_AlturaEquino.setText("");
        cx_CodAnimal.setText("");
        cx_IdadeEquino.setText("");
        cx_PerimetroEquino.setText("");
        cx_CodAnimal.requestFocus();
    }
    
    public void sair(){
        int resp = JOptionPane.showConfirmDialog(
                null,
                "Deseja realmente sair?",
                "Saida",
                JOptionPane.YES_NO_OPTION
        );
        if(resp == 0){
            dispose();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_CodAnimal = new javax.swing.JLabel();
        cx_CodAnimal = new javax.swing.JTextField();
        lb_IdadeAnimal = new javax.swing.JLabel();
        cx_IdadeEquino = new javax.swing.JTextField();
        lb_AlturaEquino = new javax.swing.JLabel();
        cx_AlturaEquino = new javax.swing.JTextField();
        lb_PerimetroToracico = new javax.swing.JLabel();
        cx_PerimetroEquino = new javax.swing.JTextField();
        btn_Cadastrar = new javax.swing.JButton();
        btn_Limpar = new javax.swing.JButton();
        lb_DoencaEquino = new javax.swing.JLabel();
        btn_DoencaSim = new javax.swing.JRadioButton();
        btn_DoencaNao = new javax.swing.JRadioButton();
        btn_Sair = new javax.swing.JButton();
        lb_CadastroEquino = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Equino");

        lb_CodAnimal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_CodAnimal.setText("Cod. Animal:");

        cx_CodAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cx_CodAnimalActionPerformed(evt);
            }
        });

        lb_IdadeAnimal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_IdadeAnimal.setText("Idade:");

        cx_IdadeEquino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cx_IdadeEquinoActionPerformed(evt);
            }
        });

        lb_AlturaEquino.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_AlturaEquino.setText("Altura:");

        cx_AlturaEquino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cx_AlturaEquinoActionPerformed(evt);
            }
        });

        lb_PerimetroToracico.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_PerimetroToracico.setText("Perimetro Toracico:");

        cx_PerimetroEquino.setToolTipText("Ex: 1.24");
        cx_PerimetroEquino.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cx_PerimetroEquinoFocusLost(evt);
            }
        });
        cx_PerimetroEquino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cx_PerimetroEquinoActionPerformed(evt);
            }
        });

        btn_Cadastrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Cadastrar.setText("Cadastrar");
        btn_Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CadastrarActionPerformed(evt);
            }
        });

        btn_Limpar.setText("Limpar");
        btn_Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LimparActionPerformed(evt);
            }
        });

        lb_DoencaEquino.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_DoencaEquino.setText("O Animal possui alguma doença?");

        btn_DoencaSim.setText("Sim");
        btn_DoencaSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DoencaSimActionPerformed(evt);
            }
        });

        btn_DoencaNao.setText("Não");
        btn_DoencaNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DoencaNaoActionPerformed(evt);
            }
        });

        btn_Sair.setText("Sair");
        btn_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SairActionPerformed(evt);
            }
        });

        lb_CadastroEquino.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_CadastroEquino.setText("Cadastro Equino");

        jButton1.setText("Abrir Relatório de Animais");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 84, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_DoencaSim)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_DoencaNao))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lb_PerimetroToracico)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cx_PerimetroEquino, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lb_IdadeAnimal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cx_IdadeEquino, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lb_DoencaEquino)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lb_AlturaEquino)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cx_AlturaEquino, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lb_CadastroEquino))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_Cadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Limpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Sair)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lb_CodAnimal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cx_CodAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(65, 65, 65))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lb_CadastroEquino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lb_CodAnimal)
                    .addComponent(cx_CodAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(cx_IdadeEquino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_IdadeAnimal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(cx_AlturaEquino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_AlturaEquino))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(cx_PerimetroEquino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_PerimetroToracico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_DoencaEquino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_DoencaSim)
                    .addComponent(btn_DoencaNao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Cadastrar)
                    .addComponent(btn_Limpar)
                    .addComponent(btn_Sair))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cx_CodAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cx_CodAnimalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cx_CodAnimalActionPerformed

    private void cx_IdadeEquinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cx_IdadeEquinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cx_IdadeEquinoActionPerformed

    private void cx_AlturaEquinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cx_AlturaEquinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cx_AlturaEquinoActionPerformed

    private void cx_PerimetroEquinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cx_PerimetroEquinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cx_PerimetroEquinoActionPerformed

    private void btn_CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CadastrarActionPerformed
        insEquino();
    }//GEN-LAST:event_btn_CadastrarActionPerformed

    private void btn_DoencaSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DoencaSimActionPerformed
        btn_DoencaNao.setSelected(false);
    }//GEN-LAST:event_btn_DoencaSimActionPerformed

    private void btn_DoencaNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DoencaNaoActionPerformed
        btn_DoencaSim.setSelected(false);
    }//GEN-LAST:event_btn_DoencaNaoActionPerformed

    private void btn_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SairActionPerformed
        sair();
    }//GEN-LAST:event_btn_SairActionPerformed

    private void btn_LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LimparActionPerformed
        limpar();
    }//GEN-LAST:event_btn_LimparActionPerformed

    private void cx_PerimetroEquinoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cx_PerimetroEquinoFocusLost

    }//GEN-LAST:event_cx_PerimetroEquinoFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Relatorio_Equino.getRelAnimaisUniq().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Equino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Equino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Equino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Equino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro_Equino().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cadastrar;
    private javax.swing.JRadioButton btn_DoencaNao;
    private javax.swing.JRadioButton btn_DoencaSim;
    private javax.swing.JButton btn_Limpar;
    private javax.swing.JButton btn_Sair;
    private javax.swing.JTextField cx_AlturaEquino;
    private javax.swing.JTextField cx_CodAnimal;
    private javax.swing.JTextField cx_IdadeEquino;
    private javax.swing.JTextField cx_PerimetroEquino;
    private javax.swing.JButton jButton1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lb_AlturaEquino;
    private javax.swing.JLabel lb_CadastroEquino;
    private javax.swing.JLabel lb_CodAnimal;
    private javax.swing.JLabel lb_DoencaEquino;
    private javax.swing.JLabel lb_IdadeAnimal;
    private javax.swing.JLabel lb_PerimetroToracico;
    // End of variables declaration//GEN-END:variables
}
