/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1;

import javax.swing.JOptionPane;

/**
 *
 * @author Wes
 */
public class JanPrinc extends javax.swing.JFrame {

    /**
     * Creates new form JanPrinc
     */
    public JanPrinc() {
        initComponents();
        setLocationRelativeTo(null);
    }
    public void sair(){
        int resp = JOptionPane.showConfirmDialog(
                null,
                "Deseja realmente sair?",
                "Saida",
                JOptionPane.YES_NO_OPTION
            );
        if(resp == 0){
            dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_Principal = new javax.swing.JLabel();
        barMenuPrinc = new javax.swing.JMenuBar();
        menuPrinc = new javax.swing.JMenu();
        menuPrincCad = new javax.swing.JMenu();
        Equino = new javax.swing.JMenuItem();
        menuItem_Sair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label_Principal.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        label_Principal.setText("Principal");

        menuPrinc.setText("Principal");

        menuPrincCad.setText("Cadastrar Animal");

        Equino.setText("Equino");
        Equino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquinoActionPerformed(evt);
            }
        });
        menuPrincCad.add(Equino);

        menuPrinc.add(menuPrincCad);

        menuItem_Sair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuItem_Sair.setText("Sair");
        menuItem_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_SairActionPerformed(evt);
            }
        });
        menuPrinc.add(menuItem_Sair);

        barMenuPrinc.add(menuPrinc);

        setJMenuBar(barMenuPrinc);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(label_Principal)
                .addContainerGap(129, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(label_Principal)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItem_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_SairActionPerformed
        sair();
    }//GEN-LAST:event_menuItem_SairActionPerformed

    private void EquinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquinoActionPerformed
        Cadastro_Equino.getCadEquiUnic().setVisible(true);
    }//GEN-LAST:event_EquinoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanPrinc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanPrinc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanPrinc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanPrinc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanPrinc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Equino;
    private javax.swing.JMenuBar barMenuPrinc;
    private javax.swing.JLabel label_Principal;
    private javax.swing.JMenuItem menuItem_Sair;
    private javax.swing.JMenu menuPrinc;
    private javax.swing.JMenu menuPrincCad;
    // End of variables declaration//GEN-END:variables
}
